### ISSUE TITLE
vivek1108: Rover project rock detection, color_threshold

### ISSUE THREAD

**Issue by vxy10** [udacity/robotics-beta-test-issues#154]
Students can be introduced to thresholding based on upper and lower values so they can detect color. Will be nice to either add a module for it, or direct students to some resource where they can learn color detection. cv2.inRange function herE? http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.html

**Comment by ryan-keenan** [comment]
Thanks for the suggestion Vivek!  For now I've decided to leave the idea of imposing a threshold range as an open possibility in the project and I link to the OpenCV example using `cv2.inRange()` but I'm going to leave it out of the lesson for now to keep things more compact.  Turns out it's possible to get the rocks with just single thresholds (two `>` one `<`) so the project is doable with minor tweaks to the function given.
