### ISSUE TITLE
sagunms P1E5 Difference in colour channel representation between Matplotlib and OpenCV

### ISSUE THREAD

**Issue by sagunms** [udacity/robotics-beta-test-issues#155]
Every time we have a lesson using `mpimg` and `cv2` libraries together, students are bound to be confused between the difference in colour space representation i.e. RGB (MatPlotLib) vs BGR (OpenCV). 

So if Python will be used further in the RoboND, perhaps it will be good time to mention this right now? Otherwise, please ignore.

**Comment by ryan-keenan** [comment]
Thanks for the suggestion!  Had to think hard about this one...  I am going to leave out of the lesson for now because we're not doing any color conversions or reading images with OpenCV at this time.  I added a note near the color thresholding step in the project notebook because there I have also added a link to OpenCV docs covering a color thresholding tutorial.  We will be doing more with images using Python going forward, and will bring up this point of confusion again then to make sure people don't get screwed up.
