### ISSUE TITLE
Shreeyak P01E07: Add link to basic image operations

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#263]
While doing this project most of the functions were foreign to me. I could follow because I've worked with matlab and acessing array elements is similar there. I feel it would be beneficial to add a few links to show the basic operations like accessing channels and properties like img.shape. 
Eg: http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.html

**Comment by ryan-keenan** [comment]
Thank you for this suggestion!  I'm now linking to a [crash course on using numpy with images](http://scikit-image.org/docs/dev/user_guide/numpy_images.html) in the page called [The Perception Step](https://classroom.udacity.com/nanodegrees/nd209-beta/parts/f491093d-8e67-4eab-8102-87bae095ca79/modules/0573f9ff-2e23-48cd-87d0-af24d758348a/lessons/ef841d31-8c53-49b3-8da3-a9d1523adef0/concepts/ec04ded2-b021-4bb1-8cd4-088e38c14082).  The one you posted uses `cv2.imread()` which can confuse people because it reads images as BGR instead of RGB (i.e., blue channel is img[*,*,0], which is reversed from the way matplotlib reads images).
