### ISSUE TITLE
L03E06 - rosmsg info command

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#302]
This command is used in the lesson to obtain information about a ROS message type. I tried it and it works, but it seems that it is not a common command. The outcome is the same if you use 'rosmsg show', which seems to be the most used command.

The ROS wiki page for rosmsg (http://wiki.ros.org/rosmsg) contains a command-line tools section where 'rosmsg show' appears, but 'rosmsg info' does not. In addition, tab-completion in the command line is not supported for the info command.

**Comment by bkinman** [comment]
I've elected to use `rosmsg info` because it's more in-line with other conventions such as `rosservice info`, and `rostopic info`.

Most of the documentation on the internet still points to `rosmsg show`, because the `rosmsg info` alias is somewhat new.

Tab completion for `rosmsg info` works on my system... Strange.

To be honest though, outside of my VM I've been having problem with tab completion.

I'm going to go ahead and close this, but feel free to make additional points if you can think of any; I'm open to hear.
