### ISSUE TITLE
Introduction to Kinematics : Joint Types and Degrees of Freedom

### ISSUE THREAD

**Issue by cornzyblack** [udacity/robotics-beta-test-issues#402]
This episode says "In the previous example, we saw that two particles connected by an inextensible rod and confined to a planar surface did not have 4 degrees of freedom, only three". 

In the previous lecture, there was no explicit mention of degrees of freedom in the example, why then is this episode saying there was?

**Comment by thomas-at-em** [comment]
The goal is to break sections into small, individual concepts so that they are more easily understood. Here,  I  first present generalize coordinates and then the next lesson its degrees of freedom. The two concepts are very closely related but to keep each lesson as short as possible, I split the concepts up.
