### ISSUE TITLE
Kinematics: 7. Rotation Matrices in 2D-I can't see u vector in image.(letyrodri)

### ISSUE THREAD

**Issue by letyrodridc** [udacity/robotics-beta-test-issues#423]
I can't see *u* vector in image. Are them the (1,0) and (0,1) vectors? In some text, those vectors are represented with *e* letter. I don't see what *u* vector means.

**Comment by thomas-at-em** [comment]
No, this goes back to the previous lesson really. All vectors can be decomposed into their basis vectors (unit vectors). For example, V = a*ax_hat + b*ay_hat + c*az_hat, where a, b, and c are scalars (called measure numbers) and ax_hat, ay_hat, and az_hat are unit vectors. Because the {B} frame is rotated relative to the {A} the vector, V, will NOT have the same measure numbers when V is expressed in the {B} frame as V does when it is expressed in the {A} frame. 

The Ux and Uy in my lesson are the scalar measure numbers of V expressed in the {B} frame. What is important to recognize is that the vector is not different, it simply has different measure numbers in different reference frames.
