### ISSUE TITLE
Denavit-Hartenberg Parameter Definitions

### ISSUE THREAD

**Issue by yuvaramsingh94** [udacity/robotics-beta-test-issues#480]
is this correct 
d​i​​ (link offset) = signed distance from ​X​^​​​i−1​​ to ​X​^​​​i​​ measured along ​Z​^​​​i​​.

other online resources state we should measure d along z i-1 axis not zi axis 

https://www.youtube.com/watch?v=rA9tm0gTln8

**Comment by thomas-at-em** [comment]
As stated in "Denavit-Hartenberg Parameter Definitions":

Since its original description, several modifications have been made to the DH method, mostly regarding the numbering and location of each reference frame’s origin, so care must be taken to identify which convention is being used when comparing work from different sources, e.g.:

Waldron, KJ. A study of overconstrained linkage geometry by solution of closure equations, Part I: A method of study (1973). Mech. Mach. Theory 8(1):95-104.
Paul, R. (1982). Robot Manipulators: Mathematics, Programming and Control (MIT Press, Cambridge, MA)
Craig, JJ. (2005). Introduction to Robotics: Mechanics and Control, 3rd Ed (Pearson Education, Inc., NJ)
Khalil, W and Dombre, E. (2002). Modeling, Identification and Control of Robots (Taylor Francis, NY)
Because of the differences in convention, it can make the comparison of results more difficult. It is important to always check how the sequence of homogeneous transforms is performed to relate neighboring links. The convention described below is consistent with Craig, (2005).
