### ISSUE TITLE
tantony L02E07

### ISSUE THREAD

**Issue by thomasantony** [udacity/robotics-beta-test-issues#543]
It might be helpful to explicitly specify that the rover is always assumed to be at the position:
(img_width/2, img_height) in pixel coordinates, before doing the coordinate transformation.

The expression is directly used in the solution to the quiz without any follow-up on why it was done so.

**Comment by sahiljuneja** [comment]
I think this was kind of implied when the rover camera coordinates were mentioned in the text above the image. But I will add some text to make it slightly more clear. Thanks!

Also, for any subsequent feedback/issues please mention the Lesson name or the Section Name as well in the Title. Like "Intro to Robotics" or "Search and Sample Return". Since each section has independent lesson numbers, L02 can be slightly confusing initially :)
