### ISSUE TITLE
Hyperlinks not working

### ISSUE THREAD

**Issue by alvarovillena** [udacity/robotics-beta-test-issues#582]
The links in the lessons to other parts of the course are not working for me.
e.g. [This link](https://classroom.udacity.com/nanodegrees/nd209/parts/586e8e81-fc68-4f71-9cab-98ccd4766cfe/modules/e5bfcfbd-3f7d-43fe-8248-0c65d910345a/lessons/2cc29bbd-5c51-4c3e-b238-1282e4f24f42/concepts/57f2601e-7f58-4873-aead-70ba96da270f) appears in the last project, perception pipeline section. When I try to follow it, the following message pops up: `You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?`

This is happening in every lesson, I tested it trying to access to links in previous sections that were working before.

**Comment by sahiljuneja** [comment]
Hey. Yes, that's a known problem. It's difficult to have two separate sets of links for beta-testers and regular students, so that problem arises. So right now, it's unlikely to be fixed so that you can easily jump to the linked lesson.

But all the links refer to content you would have gone through during Perception. But I will modify the text such that it can be a bit more clear to what it's corresponding to. Quite a few links have text that clarifies it to an extent and you can make that out from context, but if you notice any specific ones then comment here and I will see how we can clear it up.
