### ISSUE TITLE
Project - Where am I - Update first rubric point

### ISSUE THREAD

**Issue by Shreeyak** [udacity/robotics-beta-test-issues#763]
The first rubric point simply mentions checking all files. It will be very helpful here to provide a list of all required files. I believe this is done in other projects? 

Here's the first rubric point as it is now:
```
The student submitted all required files specified in the criteria.

Tip
Please make sure you first check all of the files and make sure they are present. If they are not present, do not fail the student on this point but mark the whole project as "cannot review" and explain to student what file is missing.

All images must be watermarked with the student's first and last name.
```

**Comment by sahiljuneja** [comment]
Well, since you beta-tested the project all files should have been easy to check. Also being able to run the project without issue is perhaps the easiest way to check on this, although, not sure whether that's more time consuming than checking all files or not. 

There might be an update to the project repo soon which might make things easier for students and reviewers alike. Will update once that's ready and can then see if more information will be required or not around this.

**Comment by Shreeyak** [comment]
Yes, we don't need to check all the files inside the package.
The requirements are mentioned in the rubric, under criteria: "Include in
your project submission your write-up (PDF format), supporting images, and
the entire ROS package you created."

Simply asking to add the same as bullet points under "meets specifications"
to make it easier while reviewing.
Here is the rubric, check the second point. Just doing the same for the
first point would help: https://review.udacity.com/#!/rubrics/1365/view

Thanks
